### ISSUE TITLE
Laser Location issues

### ISSUE THREAD

**Issue by gabrielchan2002** [Gallo-ICS2O1a/cpt-gabriel#1]
Don't understand how to bind y location of laser back to player y location after laser has passed the edge of the screen

**Comment by MrGallo** [comment]
Did you try `laserY = playerY`?

**Comment by gabrielchan2002** [comment]
Yes, ive tried laser_loc.y = pos.y but im not sure where to put it

**Comment by gabrielchan2002** [comment]
got it
