### ISSUE TITLE
Retry() function issues

### ISSUE THREAD

**Issue by gabrielchan2002** [Gallo-ICS2O1a/cpt-gabriel#3]
The frameCount resets in the retry() function to 0, but it won't reset in the draw loops, which doesn't reset the scrolling background to start at the beginning again.

**Comment by MrGallo** [comment]
I don't see where you are setting the `frameCount` to 0.
https://github.com/Gallo-ICS2O1a/cpt-gabriel/blob/79b5384ae3de81f00459c8035b3c029e8d92ecfa/CPT.pyde#L45-L60

**Comment by MrGallo** [comment]
Updating the frameCount manually has strange results anyway.
Just create your own custom frame counter.
```python
# Create your own frame counter
frames = 0

def setup():
    size(400, 400)
    
    
def draw():
    global frames
    background(255)
    
    # Draw the custom frame count
    textSize(40)
    fill(0)
    textAlign(CENTER)
    text(frames, width/2, height/2)
    
    # manually increase the custom frame count every draw cycle
    frames += 1


def mousePressed():
    # Reset the custom frame count
    global frames
    frames = 0
```

**Comment by MrGallo** [comment]
**OR**
Save a snapshot of the `frameCount` and use that to subtract from the continuous `frameCount`.
In the `reset()` function:
```python
frames = frameCount
```
Then in the `draw()` function, to zero the frames, you just subtract the `frames` "snapshot" from the current `frameCount`.  
```python
background_x = frameCount - frames
```
